version: "2"
services:
  qgisserver:
    restart: always
    image: gisquick/qgis-server
#    image: kartoza/qgis-server:3.0
    volumes:
      - ./_data/publish:/publish/:ro
    ports:
      - "9000:90"

  django:
    restart: always
    image: docker.io/davidtethal/gisquick-vue
#    image: gisquick/django
    links:
      - qgisserver
    volumes:
      - ./_data/data/:/var/www/gisquick/data/
      - ./_data/media/:/var/www/qisquick/media/
      - ./_data/publish:/publish/
    environment:
      - GUNICORN_WORKERS=2
      - GUNICORN_ERRORLOG=-
      - GUNICORN_ACCESSLOG=-
      - DJANGO_GISQUICK_MAPSERVER_URL='http://192.168.0.16:90/cgi-bin/qgis_mapserv.fcgi'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  nginx:
    restart: unless-stopped
    image: gisquick/nginx
    links:
      - django
    volumes_from:
      - django:ro
    volumes:
      - ./_data/etc/letsencrypt/:/etc/letsencrypt/
      - ./_data/var/www/certbot/:/var/www/certbot/
    ports:
      - "443:443"
    environment:
      - NGINX_HOST=server
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"